------------------------------------------------------------
-- [여기부터 4줄 관리자 계정접속해서 'jbj_user'계정 생성]
------------------------------------------------------------
--ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
---- 계정 생성
--CREATE USER jbj_user IDENTIFIED BY jbj_pass123;
---- 권한 부여
--GRANT CONNECT, RESOURCE, CREATE VIEW TO jbj_user;
---- 객체 생성 공간 할당성
--ALTER USER jbj_user DEFAULT TABLESPACE SYSTEM
--QUOTA UNLIMITED ON SYSTEM;
--COMMIT;

------------------------------------------------------------
-- ['jbj_user'계정 젒속하여 init.sql 실행]
------------------------------------------------------------
-- JBJ Database 초기화 스크립트

-- LEVELS 테이블 생성
DROP TABLE "LEVELS";
CREATE TABLE LEVELS (
    LEVEL_NO NUMBER NOT NULL,
    REQUIRED_TOTAL_EXP NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_LEVELS PRIMARY KEY (LEVEL_NO)
);

COMMENT ON COLUMN LEVELS.LEVEL_NO IS 'LV1 ~ LV30';
COMMENT ON COLUMN LEVELS.REQUIRED_TOTAL_EXP IS '레벨별 필요 누적 경험치';
COMMENT ON COLUMN LEVELS.TITLE IS '레벨별 타이틀';

--SELECT * FROM "LEVELS";
--SELECT SEQ_LEVEL_NO.NEXTVAL from dual; -- 시퀀스없으면 에러: ORA-02289: sequence does not exist
--DELETE FROM "LEVELS"; 
--DROP SEQUENCE SEQ_LEVEL_NO; 
-- 시퀀스 생성
--CREATE SEQUENCE SEQ_LEVEL_NO START WITH 1 NOCACHE;

-- MEMBER 테이블 생성
CREATE TABLE MEMBER (
    MEMBER_NO NUMBER NOT NULL,
    MEMBER_EMAIL VARCHAR2(30) NOT NULL,
    MEMBER_PW VARCHAR2(200),
    MEMBER_NAME VARCHAR2(30) NOT NULL,
    MEMBER_NICKNAME VARCHAR2(30) NOT NULL,
    MEMBER_TEL VARCHAR2(13) NOT NULL,
    MEMBER_CAREER VARCHAR2(50) NOT NULL,
    MEMBER_SUBSCRIBE CHAR(1) DEFAULT 'N' NOT NULL,
    MEMBER_ADMIN CHAR(1) DEFAULT 'N' NOT NULL,
    PROFILE_IMG VARCHAR2(300),
    MEMBER_DEL_FL CHAR(1) DEFAULT 'N' NOT NULL,
    M_CREATE_DATE DATE DEFAULT SYSDATE,
    SUBSCRIPTION_PRICE NUMBER DEFAULT 0 NOT NULL,
    MY_INFO_INTRO VARCHAR2(2000),
    MY_INFO_GIT VARCHAR2(200),
    MY_INFO_HOMEPAGE VARCHAR2(200),
    BEANS_AMOUNT NUMBER DEFAULT 0 NOT NULL,
    CURRENT_EXP NUMBER DEFAULT 0 NOT NULL,
    MEMBER_LEVEL NUMBER NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NO),
    CONSTRAINT FK_LEVELS_TO_MEMBER FOREIGN KEY (MEMBER_LEVEL) REFERENCES LEVELS(LEVEL_NO),
    CONSTRAINT UK_MEMBER_EMAIL UNIQUE (MEMBER_EMAIL)
);
COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원이메일(아이디)';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원닉네임';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원전화번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_CAREER" IS '회원경력사항';
COMMENT ON COLUMN "MEMBER"."MEMBER_SUBSCRIBE" IS '회원전용메일수신동의';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADMIN" IS '관리자계정여부(Y:관리자, N:일반회원)';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';
COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원탈퇴여부';
COMMENT ON COLUMN "MEMBER"."M_CREATE_DATE" IS '회원가입일';
COMMENT ON COLUMN "MEMBER"."SUBSCRIPTION_PRICE" IS '나를구독하면 지불해야할금액: 초기값0원';
COMMENT ON COLUMN "MEMBER"."MY_INFO_INTRO" IS '내 소개글';
COMMENT ON COLUMN "MEMBER"."MY_INFO_GIT" IS '깃허브 주소';
COMMENT ON COLUMN "MEMBER"."MY_INFO_HOMEPAGE" IS '노션, 포트폴리오 등 주소';
COMMENT ON COLUMN "MEMBER"."BEANS_AMOUNT" IS '커피콩지갑';
COMMENT ON COLUMN "MEMBER"."CURRENT_EXP" IS '회원 현재 경험치';
COMMENT ON COLUMN "MEMBER"."MEMBER_LEVEL" IS 'LV1 ~ LV30';


-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- AUTH 테이블 생성
CREATE TABLE AUTH (
    AUTH_NO NUMBER NOT NULL,
    CODE VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    CREATE_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_AUTH PRIMARY KEY (AUTH_NO)
);
COMMENT ON COLUMN "AUTH"."AUTH_NO" IS '시퀀스번호';
COMMENT ON COLUMN "AUTH"."CODE" IS '인증키 코드';
COMMENT ON COLUMN "AUTH"."EMAIL" IS '이메일';
COMMENT ON COLUMN "AUTH"."CREATE_AT" IS '생성시간';

CREATE SEQUENCE SEQ_AUTH_NO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 기본 레벨 데이터 삽입
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (1,   0,     '초보자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (2,   100,   '견습 개발자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (3,   300,   '연습생');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (4,   600,   '신입 개발자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (5,   1000,  '튜토리얼 완료');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (6,   1500,  '초급 개발자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (7,   2100,  '기능 사용자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (8,   2800,  '로직 사용자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (9,   3600,  '문제 해결가');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (10,  4500,  '주니어 개발자');

INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (11,  5500,  '숙련자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (12,  6600,  '기능 숙련자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (13,  7800,  '코드 숙련자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (14,  9100,  '실전 숙련자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (15, 10500,  '실무 숙련자');

INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (16, 12000,  '중급 개발자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (17, 13600,  '설계 참여자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (18, 15300,  '안정성 담당');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (19, 17100,  '품질 담당');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (20, 19000,  '베테랑 개발자');

INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (21, 21000,  '고급 개발자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (22, 23100,  '시스템 전문가');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (23, 25300,  '문제 해결 전문가');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (24, 27600,  '핵심 멤버');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (25, 30000,  '시니어 개발자');

INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (26, 32500,  '마스터');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (27, 35100,  '그랜드 마스터');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (28, 37800,  '전설의 개발자');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (29, 40600,  '서버 네임드');
INSERT INTO LEVELS (LEVEL_NO, REQUIRED_TOTAL_EXP, TITLE) VALUES (30, 43500,  '레전드');

COMMIT;

-- =========================================================================
-- 회원 더미데이터 
INSERT INTO MEMBER VALUES (
  0,'admin@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '관리자','Administrator','0101000001','전설',
  'N','Y',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  10000000,100000,30
);
INSERT INTO MEMBER VALUES (
  SEQ_MEMBER_NO.NEXTVAL,'user01@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '김도현','NullMaster','0101000001','웹백엔드 개발자 1년차',
  'N','N',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  1000,0,1
);

INSERT INTO MEMBER  VALUES (
  SEQ_MEMBER_NO.NEXTVAL,'user02@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '이서연','버그헌터','0101000002','프론트엔드 개발자 6개월',
  'N','N',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  0,0,1
);

INSERT INTO MEMBER  VALUES (
  SEQ_MEMBER_NO.NEXTVAL,'user03@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '박지훈','코딩하는곰','0101000003','풀스택 개발자 2년차',
  'N','N',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  30,0,1
);

INSERT INTO MEMBER  VALUES (
  SEQ_MEMBER_NO.NEXTVAL,'user04@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '최민재','SQL마법사','0101000004','DBA/데이터엔지니어 3년차',
  'N','N',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  100,0,1
);

INSERT INTO MEMBER  VALUES (
  SEQ_MEMBER_NO.NEXTVAL,'user05@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '정윤호','디버깅중독','0101000005','백엔드 개발자 1년차(Spring)',
  'N','N',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  100,0,1
);

INSERT INTO MEMBER  VALUES (
  SEQ_MEMBER_NO.NEXTVAL,'user06@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '한지수','콘솔로그장인','0101000006','프론트엔드 개발자 2년차(React)',
  'N','N',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  100,0,1
);

INSERT INTO MEMBER  VALUES (
  SEQ_MEMBER_NO.NEXTVAL,'user07@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '오현우','에러수집가','0101000007','QA 엔지니어 1년차(테스트 자동화)',
  'N','N',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  100,0,1);

INSERT INTO MEMBER  VALUES (
  SEQ_MEMBER_NO.NEXTVAL,'user08@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '유채원','주석요정','0101000008','웹퍼블리셔 8개월(접근성/반응형)',
  'N','N',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  100,0,1
);

INSERT INTO MEMBER  VALUES (
  SEQ_MEMBER_NO.NEXTVAL,'user09@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '강민수','메모리도둑','0101000009','시스템 엔지니어 4년차(Linux/네트워크)',
  'N','N',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  100,0,1
);

INSERT INTO MEMBER  VALUES (
  SEQ_MEMBER_NO.NEXTVAL,'user10@devlog.com','$2a$10$XVUq9irjRcTuzgfvXeq9HuFdZf4RAJvcGQVj1Qzc20BD/ShnF0o7u',
  '신예린','리팩터여신','0101000010','풀스택 개발자 3년차(Java+JS)',
  'N','N',NULL,'N',SYSDATE,
  0,NULL,NULL,NULL,
  100,0,1
);

COMMIT;
